### PR TITLE
Favorite animation for ClassLikeNavRail

### LINKED ISSUE #611: Micro-interaction of favorite does not work when navigationBar is Rail instead of Bottom
## Overview
Please close if this is what you intended 🙇
I think it would be better to have animation even for Rail's NavigationBar.

|Bottom|Rail|
|---|---|
|<video src="https://github.com/user-attachments/assets/e0f4260d-cb26-4fa2-b05e-a580a4aac9da">|<video src="https://github.com/user-attachments/assets/0472379d-1a1c-47de-9a6f-0677fea1ff04">|

### PR DESCRIPTION
**Pull request by ked4ma**
## Issue
- close #611 

## Overview (Required)
- Add animation of favorite on timetable list when GlassLikeNavRail is displayed.
- ※Remain GlassLikeBottomNavigation's current animation.

## Links
- 

## Movie (Optional)
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/9ac46aa6-1db0-4e25-a49e-009484c1af87" width="300" > | <video src="https://github.com/user-attachments/assets/b3c7f32a-9359-4541-bda4-0517c5156252" width="300" >
<video src="https://github.com/user-attachments/assets/e18009bd-aa20-4b9c-a278-fa9f2adef38a" width="300" > | <video src="https://github.com/user-attachments/assets/2980a7fd-c9a8-415e-b0ba-bda261d869f6" width="300" >

### CODE REVIEW

File: core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/animation/FavoriteAnimationScope.kt [hunk 1]
```diff
@@ -22,11 +22,11 @@ internal val LocalFavoriteAnimationScope: ProvidableCompositionLocal<FavoriteAni
 internal fun FavoriteAnimationScope(
     clock: Clock,
     coroutineScope: CoroutineScope,
-    isEnabled: Boolean,
+    direction: FavoriteAnimationDirection,
```
Comment (ked4ma) [inline core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/animation/FavoriteAnimationScope.kt:25]: By this pr, FavoriteAnimation is called. so I removed `isEnabled` and introduced `direction` instead of this to adjust  animation.

**Review by takahirom — APPROVED** [review]
Looks great! Thank you for your contribution!
