### PR TITLE
Fix Staff API url and return actual value

### LINKED ISSUE #386: Use this year's Staff API
It will be `/events/droidkaigi2024/staff`

https://github.com/DroidKaigi/conference-app-2024/blob/a3d0c2a8e928b1c5c35c454086321535ded66a52/core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/staff/StaffApiClient.kt#L17

And please comment in the API and check the screen.
https://github.com/DroidKaigi/conference-app-2024/blob/a3d0c2a8e928b1c5c35c454086321535ded66a52/core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/staff/StaffApiClient.kt#L31-L34

### PR DESCRIPTION
**Pull request by r-kuno-zer0**
## Issue
- close #386

## Overview (Required)
- I fixed the StaffApi url in [StaffApiClient.kt](https://github.com/DroidKaigi/conference-app-2024/blob/a3d0c2a8e928b1c5c35c454086321535ded66a52/core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/staff/StaffApiClient.kt#L17)
- I added comment in the API

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After
:--: | :--:
 |

### CODE REVIEW

File: core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/staff/StaffApiClient.kt [hunk 1]
```diff
@@ -9,12 +9,16 @@ import io.github.droidkaigi.confsched.data.NetworkService
...
 import io.github.droidkaigi.confsched.data.staff.response.StaffsResponse
 import io.github.droidkaigi.confsched.model.Staff
-import io.github.droidkaigi.confsched.model.fakes
 import kotlinx.collections.immutable.PersistentList
 import kotlinx.collections.immutable.toPersistentList
 
 internal interface StaffApi {
-    @GET("/events/droidkaigi2023/staff")
+    /**
+     * Gets staff information for the DroidKaigi 2024 event.
```
Comment (takahirom) [inline core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/staff/StaffApiClient.kt:17]: 👍

**Review by takahirom — APPROVED** [review]
Thank you for your contribution!
