### PR TITLE
Fixed tab on timetable. (This design may change soon)

### LINKED ISSUE #291: Better Timetable tabs for iOS
iOS tabs for timetable is just buttons right now. The button color and text should at minimum change when selected/not selected.

### PR DESCRIPTION
**Pull request by charles-b-stb**
## Issue
- close #291

## Overview (Required)
- Fixed basic tab functionality for iOS

## Links
- 

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After
:--: | :--:
スクリーンショット 2024-08-11 20 53 52 | スクリーンショット 2024-08-12 17 46 06

## Movie (Optional)
Before | After
:--: | :--:
<video src="" width="300" > | <video src="" width="300" >

### CODE REVIEW

**Comment by shin-usu** [comment]
@charles-b-stb 
I think there are difference between your implementation tab and figma design one...!!

### Your implementation


### Figma
[Figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54888-45493&t=foCXxsn6TgrHThiV-4)

**Comment by charles-b-stb** [comment]
@shin-usu Fixed

File: app-ios/Sources/TimetableFeature/TimetableListView.swift [hunk 1]
```diff
@@ -13,18 +13,33 @@ public struct TimetableView: View {
...
+                            .foregroundStyle(AssetColors.Custom.iguana.swiftUIColor)
+                            .padding(6)
+                        } else {
+                            HStack(spacing: 6) {
+                                Text(tabItem.rawValue)
+                                    .textStyle(.labelMedium)
+                            }
+                            .foregroundStyle(AssetColors.Surface.onSurface.swiftUIColor)
+                            .padding(6)
+                        }
```
Comment (shin-usu) [inline app-ios/Sources/TimetableFeature/TimetableListView.swift:42]: I think following code is better because it is short and clear what is changed👀 
```suggestion
                        HStack(spacing: 6) {
                                Text(tabItem.rawValue)
                                    .textStyle(.labelMedium)
                                    .underline(selectedTab == tabItem)
                            }
                            .foregroundStyle(selectedTab == tabItem ? AssetColors.Custom.iguana.swiftUIColor : AssetColors.Surface.onSurface.swiftUIColor)
                            .padding(6)
```

File: app-ios/Sources/TimetableFeature/TimetableListView.swift [hunk 2]
```diff
@@ -13,18 +13,33 @@ public struct TimetableView: View {
...
+                        selectedTab = tabItem
                     }, label: {
                         //TODO: Only selected button should be green and underlined
-                        Text(tabItem.rawValue).foregroundStyle(
-                            AssetColors.Custom.flamingo.swiftUIColor)
-                            .underline()
+                        if selectedTab == tabItem {
+                            HStack(spacing: 6) {
+                                Text(tabItem.rawValue)
+                                    .textStyle(.labelMedium)
```
Comment (shin-usu) [inline app-ios/Sources/TimetableFeature/TimetableListView.swift:30]: I think title medium text style is correct.
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54888-45511&t=ksxzQYBOQy0QhDQQ-4

File: app-ios/Sources/TimetableFeature/TimetableListView.swift [hunk 3]
```diff
@@ -13,18 +13,33 @@ public struct TimetableView: View {
...
     
     public var body: some View {
         VStack {
             HStack {
                 ForEach(DayTab.allCases) { tabItem in
                     Button(action: {
                         store.send(.view(.selectDay(tabItem)))
+                        selectedTab = tabItem
                     }, label: {
                         //TODO: Only selected button should be green and underlined
```
Comment (shin-usu) [inline app-ios/Sources/TimetableFeature/TimetableListView.swift:26]: Can you delete this todo comment?

File: app-ios/Sources/TimetableFeature/TimetableListView.swift (hunk 2 above)
Comment (charles-b-stb) [reply app-ios/Sources/TimetableFeature/TimetableListView.swift:29]: Fixed

**Comment by charles-b-stb** [comment]
@shin-usu  Fixed as per suggestions.

File: app-ios/Sources/TimetableFeature/TimetableListView.swift (hunk 3 above)
Comment (shin-usu) [reply app-ios/Sources/TimetableFeature/TimetableListView.swift:26]: @charles-b-stb 
What do you think?

File: app-ios/Sources/TimetableFeature/TimetableListView.swift [hunk 4]
```diff
@@ -13,18 +13,24 @@ public struct TimetableView: View {
...
-                        Text(tabItem.rawValue).foregroundStyle(
-                            AssetColors.Custom.flamingo.swiftUIColor)
-                            .underline()
+                        HStack(spacing: 6) {
+                                Text(tabItem.rawValue)
+                                .textStyle(.titleMedium)
+                                    .underline(selectedTab == tabItem)
+                            }
+                            .foregroundStyle(selectedTab == tabItem ? AssetColors.Custom.iguana.swiftUIColor : AssetColors.Surface.onSurface.swiftUIColor)
+                            .padding(6)
```
Comment (shin-usu) [inline app-ios/Sources/TimetableFeature/TimetableListView.swift:33]: Thank you for the correction!
But it seems like the indent is wrong. (Why doesn't SwiftLint detect it...???)

**Review by shin-usu — COMMENTED** [review]
I left some comments!
And could you please confirm this comment that is left earlier??
https://github.com/DroidKaigi/conference-app-2024/pull/299/files#r1713903080

File: app-ios/Sources/TimetableFeature/TimetableListView.swift (hunk 3 above)
Comment (charles-b-stb) [reply app-ios/Sources/TimetableFeature/TimetableListView.swift:26]: somehow I missed this. I think its because I was doing two PRs at once and removed a different TODO from the other PR.

File: app-ios/Sources/TimetableFeature/TimetableListView.swift (hunk 4 above)
Comment (charles-b-stb) [reply app-ios/Sources/TimetableFeature/TimetableListView.swift]: I think this is fixed now?

Comment (shin-usu) [reply app-ios/Sources/TimetableFeature/TimetableListView.swift]: I seems like It isn't fixed.
The indentation of HStack and Text is off by a large amount. I think it should be fixed.

**Comment by charles-b-stb** [comment]
https://github.com/DroidKaigi/conference-app-2024/pull/299#discussion_r1715183706

Sorry I am not certain what this is referring to. Do you mean the TODO? I removed that. 
Is it something else?

> What do you think?

I am not sure exactly what this is referring to.

File: app-ios/Sources/TimetableFeature/TimetableListView.swift (hunk 4 above)
Comment (charles-b-stb) [reply app-ios/Sources/TimetableFeature/TimetableListView.swift]: I tried again, if its still not fixed, please let me know the exact amount needed to fix it.

🙇 

My screen is small so I think it displays differently on my device than what you are seeing.

**Comment by charles-b-stb** [comment]
@shin-usu sorry for how many times this has taken. I updated the pull request.

Please help me understand the comment you have wanted me to look at. I confused it for other things and its really not clear to me now what you mean by the comment.

**Comment by shin-usu** [comment]
@charles-b-stb 
OK, I will fix and push this branch.

**Comment by shin-usu** [comment]
@charles-b-stb 
What I wanted corrected is the content of this commit. Thx!
https://github.com/DroidKaigi/conference-app-2024/pull/299/commits/ed2ae57528a88cfad00044ee3b09812f5289623f

**Review by shin-usu — APPROVED** [review]
LGTM!
