### PR TITLE
:wrench: [iOS・Compose Multiplatform] The issue where the bottom navigation overlapped with the Create Profile button and made it difficult to press has been fixed.

### LINKED ISSUE #905: [iOS・Compose Multiplatform] Bottom tab bar is covering create card button
# Overview

On the iOS app, the bottom tab bar is covering the create card button on the profile card screen.

# Screenshot

### PR DESCRIPTION
**Pull request by Corvus400**
## Issue
- close #905

## Overview (Required)
- I simply added 30.dp to the bottom.
- As I mentioned in the comments, I think it would be better to get the inset from the iOS side as a permanent measure and set the padding in ProfileCardScreen based on that.

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before iPad mini | After iPad mini
:--: | :--:
 | 

Before iPhone 15 | After iPhone 15 
:--: | :--:
 | 

Before iPhone SE 3rd gen | After iPhone SE 3rd gen 
:--: | :--:
 |

### CODE REVIEW

File: feature/profilecard/src/iosMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardViewController.kt [hunk 1]
```diff
@@ -22,6 +24,10 @@ fun profileCardViewController(
                 imageBitmap.toUiImage() ?: UIImage(),
             )
         },
+        // FIXME This is a workaround. For permanent support, we will get the inset value etc. from the iOS side and respond.
+        contentPadding = PaddingValues(
+            bottom = 30.dp,
```
Comment (takahirom) [inline feature/profilecard/src/iosMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardViewController.kt:29]: Now, I understand that we don't exceed the height of the bottom tab bar, right? Could we add a comment like this?

```suggestion
            bottom = 30.dp, // Hight of bottom tab bar
```

**Comment by takahirom** [comment]
Thank you for your contribution!
