### PR TITLE
Fix/bottom bar navigation

### LINKED ISSUE #344: Bug: When you move to the bottom navigation and then go back, the bottom navigation tab does not change.
## Problem
We have identified a bug in the bottom navigation system. The issue manifests as follows:

After moving to another screen using the bottom navigation bar, when you press back to return to the main screen, the bottom navigation bar tab does not change to the main screen. 
(It is the main screen, but the screen tab that was moved before going back is maintained.)

https://github.com/user-attachments/assets/0ab9115f-8d22-49b9-91b3-275251a7e079

### PR DESCRIPTION
**Pull request by hiroaki404**
## Issue
- close #344

## Overview (Required)
- My guess is that #344 is resolved by #317 partialy when going to the sub screen and back, but not resolved or regressed for the screen at the top of the tab.
I fix back navigation to top of the tab. When back to screen, change selected tab in bottom bar.

## Links
- 

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before | After
:--: | :--:
 | 

## Movie (Optional)
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/34528012-2c52-4707-8ec1-3543ae467d5f" width="300" > | <video src="https://github.com/user-attachments/assets/f8dab9cb-0036-4f58-92e1-2c1b1c34c930" width="300" >

### CODE REVIEW

File: app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt [hunk 1]
```diff
@@ -228,6 +229,7 @@ class KaigiAppMainNestedGraphStateHolder : MainNestedGraphStateHolder {
     override val startDestination: String = timetableScreenRoute
 
     override fun routeToTab(route: String): MainScreenTab? {
+        if (route.contains(EventMapDestination::class.java.simpleName)) return EventMap
```
Comment (takahirom) [inline app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt:232]: Well, it is nullable, but can we use EventMapDestination::class.simpleName for KMP? We could potentially reuse this later.

File: feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeBottomNavigation.kt [hunk 2]
```diff
@@ -239,18 +229,3 @@ fun BottomBarTabs(
         }
     }
 }
-
-@Preview
-@Composable
-fun GlassLikeBottomNavigationPreview() {
```
Comment (takahirom) [inline feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeBottomNavigation.kt:245]: May I ask why we need to remove this? We are using this for screenshot tests.

Comment (hiroaki404) [reply feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeBottomNavigation.kt:245]: Sorry, I guess I didn't fully understand how the screenshot test works, I had a warning in the IDE lint, so I turned it off, but I'll put it back on.

File: app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt (hunk 1 above)
Comment (hiroaki404) [reply app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt:232]: I had forgotten that it was KMP. I will think little bit.

Comment (hiroaki404) [reply app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt]: I understood. if we use java's simpleName, we will have problems when this modified to support KMP.
So I use Kotlin's simpleName here, and I have confirmed that I can use Kotlin's simpleName in iOS without any problems.

File: feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeNavRail.kt [hunk 3]
```diff
@@ -75,13 +73,13 @@ fun GlassLikeNavRail(
                 shape = CircleShape,
             ),
     ) {
-        NavRailTabs(selectedTab = selectedTabIndex, onTabSelected = {
-            selectedTabIndex = MainScreenTab.indexOf(it)
-            onTabSelected(it)
-        })
+        NavRailTabs(
+            selectedTab = currentTab.ordinal,
```
Comment (takahirom) [inline feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeNavRail.kt:77]: I believe that if we use ordinal, we should remove the indexOf method. However, I prefer indexOf over ordinal because ordinal is dependent on the code order. Using ordinal would require us to change numerous places in our code if we want to implement logic such as hiding tabs.

**Review by takahirom — APPROVED** [review]
Anyway, Thank you for fixing the bug and your contribution!
