### PR TITLE
Fixed “Create Card” button could not be tapped when the keyboard was displayed

### LINKED ISSUE #852: Can't tap the "Create Card" button when the keyboard is displayed
Can't tap the “Create Card” button when the keyboard is displayed.
Therefore, the keyboard must be closed once, which is a poor user experience.

### PR DESCRIPTION
**Pull request by kubode**
## Issue
- close #852

## Overview (Required)
- Can't tap the “Create Card” button when the keyboard is displayed. Therefore, the keyboard must be closed once, which is a poor user experience.

## Links
- 

## Movie (Optional)
Before | After
:--: | :--:
 | <video src="https://github.com/user-attachments/assets/1ecd9be7-ba7c-4e7c-86d0-c84b708fd9e2" width="300" >

### CODE REVIEW

File: feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt [hunk 1]
```diff
@@ -74,10 +75,12 @@ import androidx.compose.ui.graphics.vector.rememberVectorPainter
 import androidx.compose.ui.input.nestedscroll.nestedScroll
 import androidx.compose.ui.input.pointer.pointerInput
 import androidx.compose.ui.layout.ContentScale
+import androidx.compose.ui.platform.LocalDensity
 import androidx.compose.ui.platform.LocalLayoutDirection
 import androidx.compose.ui.platform.LocalSoftwareKeyboardController
 import androidx.compose.ui.platform.testTag
 import androidx.compose.ui.unit.dp
+import androidx.compose.ui.unit.max
```
Comment (takahirom) [inline feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt:83]: I didn't know this function!

File: feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt [hunk 2]
```diff
@@ -239,6 +242,10 @@ internal fun ProfileCardScreen(
         }
     }
 
+    val contentWindowInsetsBottom = max(
+        contentPadding.calculateBottomPadding(),
+        with(LocalDensity.current) { WindowInsets.ime.getBottom(this).toDp() },
```
Comment (takahirom) [inline feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt:247]: 👍

**Review by takahirom — APPROVED** [review]
I love your code! Thank you for your contribution.
