### PR TITLE
Timetable text appearance alignments

### LINKED ISSUE #333: Several components in the timetable don't use the current font and style
There are more things here than I highlighted in the image below, but we should take them in small chunks. For now, I'd like to highlight some incorrect font usages on the timetable screen (both for list and grid). I'll be taking this on myself, PR incoming shortly.

before

### PR DESCRIPTION
**Pull request by mannodermaus**
## Issue
- close #333

## Overview (Required)
- Update several components of the `TimetableList` screen to use the correct text styles and appearance
- Update several components of the `TimetableGrid` screen to use the correct text styles and appearance

## Links
- Expected design is based on [Figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54795-26746&t=agwbDcGBmYwrCwd5-0)

## Screenshot (Optional if screenshot test is present or unrelated to UI)

after

### CODE REVIEW

**Comment by takahirom** [comment]
Thanks as always!
Thank you for finding so many areas for improvement! Regarding the title of the grid item, we already have the issue and assigner. Could you please leave it as it is?
https://github.com/DroidKaigi/conference-app-2024/issues/225

**Comment by mannodermaus** [comment]
@takahirom Thanks for the review! I didn't see the other issue for the grid item title, I will revert it. As for the expected screenshot test failures for the rest, how do I regenerate the reference images?

**Comment by takahirom** [comment]
There are pros and cons to this approach. We don't manage screenshots in git, and the single source of truth for screenshots is the GitHub Artifact of the main branch. Consequently, when you push changes, the screenshots will be updated automatically.

**Comment by mannodermaus** [comment]
Okay, understood. I still see some odd alignments in the new images, so let me deal with those first.

**Comment by mannodermaus** [comment]
@takahirom I added two commits to address the previous discussion points. 🙇‍♂️

1) [Revert flipping of title+date for TimetableGridItem](https://github.com/DroidKaigi/conference-app-2024/pull/336/commits/3e0c77516db1f7da54dd9b79f7e016ec634fad04)

This should unblock the work in #225. I kept the part where a border is added to align more closely with Figma:

before


2) [Update incorrect alignment of multiple speakers in TimetableItemCard](https://github.com/DroidKaigi/conference-app-2024/pull/336/commits/87d0fa8066bb35f5c16f2fd17374a12303c4c311)

This addresses the issue I noticed while looking at the Roborazzi output (missing vertical padding between multiple speakers in TimetableItemCard):

|Before|After|
|---|---|
|before|after|

File: core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/component/TimetableItemCard.kt [hunk 1]
```diff
@@ -53,69 +53,84 @@ fun TimetableItemCard(
...
+                if (timetableItem.speakers.isNotEmpty()) {
+                    Spacer(Modifier.height(4.dp))
+
+                    timetableItem.speakers.forEach { speaker ->
+                        Row(
+                            modifier = Modifier.padding(top = 4.dp),
+                            verticalAlignment = Alignment.CenterVertically,
+                            horizontalArrangement = Arrangement.spacedBy(8.dp),
+                        ) {
+                            // TODO: Fixed image loading again but its still slow. Maybe we need smaller images?
```
Comment (takahirom) [inline core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/component/TimetableItemCard.kt:91]: 👍

**Comment by takahirom** [comment]
@mannodermaus 
Thanks! I think this is a great improvement in fidelity to Figma. Do you have any idea what's happening here?
image

**Comment by mannodermaus** [comment]
Oh, oops. Yes, I do – it's related to some refactoring of the rows+columns of the card. Cheers to Roborazzi for catching this stuff so nicely, I love it. Addressed by 867c2da62468c75ef92783c95d3d0cc81aa0e124!

**Review by takahirom — APPROVED** [review]
Thank you for your contribution! I'm going to change the readme image based on these changes.
