### PR TITLE
Fix window insets to avoid overlapping display cutouts and system bars

### LINKED ISSUE #963: When using landscape orientation and 3-button navigation, unnecessary padding is created and the layout is broken
## Overview
The layout of the three-button navigation system is not always correct when the screen is turned horizontally.

|name|image|
|---|---|
|TimetableList||
|TimetableGrid|||
|SponsorsScreen|||
|ProfileCardScreen|||
|TimetableitemDetailScreen|||

### PR DESCRIPTION
**Pull request by norihirosunada**
## Issue
- close #963 

## Overview (Required)
- fixed the whole screen horizontal padding to edge-to-edge
- applied window insets to avoid overlapping display cutouts and system bars for each screens

## Screenshot (Optional if screenshot test is present or unrelated to UI)
Before (90° Clockwise) | After (90° Clockwise)
:--: | :--:
 | 
 | 
 | 
 | 
 | 
 | 
 | 
 | 
 | 
 | 
 | 
 | 
 | 

Before (90° Counter Clockwise) | After (90° Counter Clockwise)
:--: | :--:
 | 
 | 
 | 
 | 
 | 
 | 
 | 
 | 
 | 
 | 
 | 
 | 
 |

### CODE REVIEW

File: app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt [hunk 1]
```diff
@@ -112,14 +104,7 @@ fun KaigiApp(
...
                 displayFeatures = displayFeatures,
-                modifier = Modifier.padding(
-                    start = WindowInsets.displayCutout
-                        .asPaddingValues()
-                        .calculateStartPadding(layoutDirection),
-                    end = WindowInsets.displayCutout
-                        .asPaddingValues()
-                        .calculateEndPadding(layoutDirection),
-                ),
+                modifier = Modifier.fillMaxSize(),
```
Comment (takahirom) [inline app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt:107]: 👍

File: feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt [hunk 2]
```diff
@@ -131,6 +133,11 @@ fun EventMapScreen(
             AnimatedTextTopAppBar(
                 title = stringResource(EventMapRes.string.eventmap),
                 scrollBehavior = scrollBehavior,
+                windowInsets = WindowInsets(
+                    left = contentPadding.calculateLeftPadding(layoutDirection),
```
Comment (takahirom) [inline feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt:137]: Thank you for the amazing PR! I'll merge it regardless. However, could you explain why the window insets of each screen's AnimatedTextTopAppBar are different?

Comment (norihirosunada) [reply feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt:137]: @takahirom 
I gave this window insets to avoid display cutouts and system bars, since default value `TopAppBarDefaults.windowInsets` only  avoids system bars.

Comment (takahirom) [reply feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt:137]: Thanks for your explain. How about making a function like this? And can you resolve the conflict with the main branch?



```kotlin
windowInsets = AnimatedTextTopAppBarDefaults.windowInsets(contentPadding),
```

```kotlin
object AnimatedTextTopAppBarDefaults {
    @Composable
    fun windowInsets(contentPadding: PaddingValues): WindowInsets {
        val layoutDirection = LocalLayoutDirection.current
        return WindowInsets(
            left = contentPadding.calculateLeftPadding(layoutDirection),
            top = contentPadding.calculateTopPadding(),
            right = contentPadding.calculateRightPadding(layoutDirection),
        )
    }
}
```

Comment (norihirosunada) [reply feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt:137]: Yes of course!

Comment (norihirosunada) [reply feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt:137]: @takahirom 
I realized I didn't need to use content padding for window insets of top app bars. 
I'll make default windowInsets like below for each top app bars instead.

```kotlin
object HogeTopAppBarDefaults {
    val windowInsets = WindowInsets.displayCutout.union(WindowInsets.systemBars).only(
        WindowInsetsSides.Horizontal + WindowInsetsSides.Top,
    )
}
```

**Comment by takahirom** [comment]
@norihirosunada Sorry for keeping you disturbed, but could you resolve the conflict? 🙇

**Comment by norihirosunada** [comment]
@takahirom 
Conflict resolved 👍

**Comment by takahirom** [comment]
Let's merge! (Sorry, I've just released. I'm not sure if I can release this.)

**Comment by takahirom** [comment]
Anyway Thank you for your contribution!
